name = "PixelBoost"
client_id = "20aac217d4fe94063de7e255cb7a712c"
application_url = "https://pixelboost.onkra.online/"
embedded = true


[access_scopes]
scopes = "write_products,write_files"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://pixelboost.onkra.online/auth/callback",
  "https://pixelboost.onkra.online/auth/shopify/callback",
  "https://pixelboost.onkra.online/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "https://pixelboost.onkra.online/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
